/* See COPYRIGHT for copyright information. */

#include <inc/mmu.h>
#include <inc/memlayout.h>
#include <inc/trap.h>

#include <kern/picirq.h>


###################################################################
# exceptions/interrupts
###################################################################

/* TRAPHANDLER defines a globally-visible function for handling a trap.
 * It pushes a trap number onto the stack, then jumps to _alltraps.
 * Use TRAPHANDLER for traps where the CPU automatically pushes an error code.
 *
 * You shouldn't call a TRAPHANDLER function from C, but you may
 * need to _declare_ one in C (for instance, to get a function pointer
 * during IDT setup).  You can declare the function with
 *   void NAME();
 * where NAME is the argument passed to TRAPHANDLER.
 */
#define TRAPHANDLER(name, num)						\
	.globl name;		/* define global symbol for 'name' */	\
	.type name, @function;	/* symbol type is function */		\
	.align 2;		/* align function definition */		\
	name:			/* function starts here */		\
	pushl $(num);							\
	jmp _alltraps

/* Use TRAPHANDLER_NOEC for traps where the CPU doesn't push an error code.
 * It pushes a 0 in place of the error code, so the trap frame has the same
 * format in either case.
 */
#define TRAPHANDLER_NOEC(name, num)					\
	.globl name;							\
	.type name, @function;						\
	.align 2;							\
	name:								\
	pushl $0;							\
	pushl $(num);							\
	jmp _alltraps

.text

/*
 * Lab 3: Your code here for generating entry points for the different traps.
 */

TRAPHANDLER_NOEC(t_divide, T_DIVIDE);    // 0
TRAPHANDLER_NOEC(t_debug, T_DEBUG);      // 1
TRAPHANDLER_NOEC(t_nmi, T_NMI);          // 2
TRAPHANDLER_NOEC(t_brkpt, T_BRKPT);      // 3
TRAPHANDLER_NOEC(t_oflow, T_OFLOW);      // 4
TRAPHANDLER_NOEC(t_bound, T_BOUND);      // 5
TRAPHANDLER_NOEC(t_illop, T_ILLOP);      // 6
TRAPHANDLER_NOEC(t_device, T_DEVICE);    // 7

TRAPHANDLER(t_dblflt, T_DBLFLT);    // 8

TRAPHANDLER(t_tss, T_TSS);          // 10
TRAPHANDLER(t_segnp, T_SEGNP);      // 11
TRAPHANDLER(t_stack, T_STACK);      // 12
TRAPHANDLER(t_gpflt, T_GPFLT);      // 13
TRAPHANDLER(t_pgflt, T_PGFLT);      // 14

TRAPHANDLER_NOEC(t_fperr, T_FPERR);      // 16

TRAPHANDLER(t_align, T_ALIGN);      // 17

TRAPHANDLER_NOEC(t_mchk, T_MCHK);        // 18
TRAPHANDLER_NOEC(t_simderr, T_SIMDERR);  // 19

TRAPHANDLER_NOEC(t_syscall, T_SYSCALL);  // 48, 0x30


// IRQ Handlers are Trap Handlers 32 -47
TRAPHANDLER_NOEC(irq0_handler, IRQ_OFFSET); 
TRAPHANDLER_NOEC(irq1_handler, IRQ_OFFSET + IRQ_KBD); 
TRAPHANDLER_NOEC(irq2_handler, IRQ_OFFSET + 2); 
TRAPHANDLER_NOEC(irq3_handler, IRQ_OFFSET + 3); 
TRAPHANDLER_NOEC(irq4_handler, IRQ_OFFSET + IRQ_SERIAL); 
TRAPHANDLER_NOEC(irq5_handler, IRQ_OFFSET + 5); 
TRAPHANDLER_NOEC(irq6_handler, IRQ_OFFSET + 6); 
TRAPHANDLER_NOEC(irq7_handler, IRQ_OFFSET + IRQ_SPURIOUS); 
TRAPHANDLER_NOEC(irq8_handler, IRQ_OFFSET + 8); 
TRAPHANDLER_NOEC(irq9_handler, IRQ_OFFSET + 9); 
TRAPHANDLER_NOEC(irq10_handler, IRQ_OFFSET + 10);
TRAPHANDLER_NOEC(irq11_handler, IRQ_OFFSET + 11); 
TRAPHANDLER_NOEC(irq12_handler, IRQ_OFFSET + 12); 
TRAPHANDLER_NOEC(irq13_handler, IRQ_OFFSET + 13); 
TRAPHANDLER_NOEC(irq14_handler, IRQ_OFFSET + IRQ_IDE); 
TRAPHANDLER_NOEC(irq15_handler, IRQ_OFFSET + 14);	 


/*
 * Lab 3: Your code here for _alltraps
 */

_alltraps:
    pushl %ds
    pushl %es
    pushal

    movl $GD_KD, %eax
    movw %ax, %ds
    movw %ax, %es

    pushl %esp

    call trap


